# Generated by Django 4.1.3 on 2024-09-13 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_categoria_libro_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='Categoria',
            new_name='categoria',
        ),
    ]
